### ISSUE TITLE
Audio Source Setter seems to be broken

### ISSUE THREAD

**Issue by DevLuckYT** [insthync/unity-audio-manager#1]
I wanted to use this audio-manager in my new unity project, but i cant get it runnig correctly. When i open the demo scene and i add a new audio-clip to the Audio Source it works, however when i remove the Audio Setter Script and add it again i get this Error:
![audio-manager-bug_or-am-i-to-stupid](https://user-images.githubusercontent.com/63712488/79322925-c8e56280-7f0d-11ea-8400-7065272036a5.PNG)

**Comment by insthync** [comment]
Fixed some time ago
